### ISSUE TITLE
[FEAT]: More Informative Image Version Tracking Commit Message

### ISSUE THREAD

**Issue by ImBIOS** [ImBIOS/bun-node#18]
### Clear and concise description of the problem

![image](https://github.com/ImBIOS/bun-node/assets/41441643/d441bfd3-71f0-42c1-8eb2-40a3998680cd)

Current:

```txt
build: update versions
```

Proposed:

```txt
build: update images version

- bun: (canary) 1.2.0-canary, (latest) 1.1.2
- nodejs: (lts-iron) 20.3.4
- distro: alpine, debian, slim
```

Add description body to the commit message for better readability and history.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ImBIOS/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ImBIOS/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
